### ISSUE TITLE
Set new_style in en_outages_clean as default.

### ISSUE THREAD

**Issue by krose** [krose/entsoeapi#11]
Hi @sbudai. Would it break anything on your end if we set the new_style as the default in the en_outages_clean function. It's a function that already tries to add a level of improvements to the default output, so why not just do the full improvement as default? Let me know what you think.

**Comment by sbudai** [comment]
Hi @krose, I use the `en_outages_clean()` function with `new_style=TRUE` argument every time. Hence it will not break anything for me. The original/previous version of this function produced that format which equals to the `new_style=FALSE` version, that is why I set the default as FALSE. The change would be OK for you and me but I do not know how many further users are affected. Noone, few or many? The choice is yours. :-)
