### ISSUE TITLE
Missing N/A

### ISSUE THREAD

**Issue by RudiHIbk01** [krose/entsoeapi#20]
Hi @krose @sbudai.
I do have a question regarding missing NA in the data that is downloaded using `entsoeapi`. The issue is the following. On some occasions there is data-points missing for some hours in the ENTSOE database (Marked in the database as N/A) (i.e. [here](https://transparency.entsoe.eu/load-domain/r2/totalLoadR2/show?name=&defaultValue=false&viewType=TABLE&areaType=BZN&atch=false&dateTime.dateTime=01.12.2018+00:00|CET|DAY&biddingZone.values=CTY|10Y1001A1001A83F!BZN|10Y1001A1001A82H&dateTime.timezone=CET_CEST&dateTime.timezone_input=CET+(UTC+1)+/+CEST+(UTC+2)) ). Now when using `en_load_day_ahead_total_load_forecast` those NA are, I guess downloaded, however dropped out and do not appear in the downloaded data, which leads to the problem that hours, or in some cases days, of data are missing. I did come up with a workaround to identify those missing hours and/or days but when dealing with years of data, this is some tidouse task to do. So my question is: Are NA downloaded using `en_load_day_ahead_total_load_forecast` but then omitted in the process of transforming the raw downloaded data in to a df? Or are NA never meant to be downloaded using the API? Which would be an issue to address towards ENTSOe because it would be kind of questionable why NA using the API would automatically be dropped out.
Thank you for your time in Advance and thank for the effort writing this package. It makes using the ENTSOe API a charm.
Cheers
Rudi

**Comment by sbudai** [comment]
Hey Rudi,

Actually your query queries 2 EIC behind the scenes.
One of them is DE-LU bidding zone (10Y1001A1001A82H) and the other one is DE country code (10Y1001A1001A83F).

You can check the API responses manually via these links:

- https://web-api.tp.entsoe.eu/api?documentType=A65&processType=A01&outBiddingZone_Domain=10Y1001A1001A82H&periodStart=201811302300&periodEnd=201812012200&securityToken=1be68e4d-ab37-4098-8c72-f4e19ec6bec0
- https://web-api.tp.entsoe.eu/api?documentType=A65&processType=A01&outBiddingZone_Domain=10Y1001A1001A83F&periodStart=201811302300&periodEnd=201812012200&securityToken=1be68e4d-ab37-4098-8c72-f4e19ec6bec0

Querying the first link now you may see that the ENTSO-E API provides only 4 datapoints for that day.

**Comment by RudiHIbk01** [comment]
Hi @sbudai.
Thank you for your answer. Once again you are having the right hint to clarify the situation. So the situation is that the API does not hand over N/A data points at all, truncating the requested time stamps to non empty data points. This is however flawed in terms of having tidy data since it makes a difference having an empty entry instead of having missing data points. I will address this to the ENTSO-E API support. Thank you also for the hint that there are actually two dedicated data streams for the “same” market area. Also, in a way weird that on the webpage one can only access DE_LU bidding zone however not the country data as in the 10Y1001A1001A83F API request. Will keep you informed about the answer of the support team, if this is something that is of interest to you. Guess the thread can be closed I guess, since you actually answered the question to its fullest.
Thank you once again. :)
