### ISSUE TITLE
en_generation_day_ahead_agg_gen()

### ISSUE THREAD

**Issue by kvink90** [krose/entsoeapi#21]
The function en_generation_day_ahead_agg_gen() does not fetch any data even though it states "downloaded", please see below: 

![01](https://github.com/krose/entsoeapi/assets/83647349/23f21407-94ec-46e5-a437-0d421eca41f8)

**Comment by sbudai** [comment]
Hey kvink90,

I am working on it, but it takes some more days.

Regards,
Sandor

**Comment by sbudai** [comment]
Hey kvink90,

It is not forgotten, but among other duties it takes more time. I will notify you when I will be ready.
Thank you for your patience!

Regards,
Sandor

**Comment by sbudai** [comment]
I think it is fixed.

Thanks for your patience!
