### ISSUE TITLE
README example is not working

### ISSUE THREAD

**Issue by sergejlazuk** [krose/entsoeapi#28]
I wanted to reproduce example shown in README, but failed on the first code snippet:

```
en_eic() |>
  filter(AreaTypeCode == "CTY", 
         AreaName == "Germany") |>
  glimpse()
```

What is `en_eic`? It is not in package namespace...

Thanks,
Sergej

**Comment by sbudai** [comment]
Hey sergejlazuk,

It is a leftover, deprecated function from a previous version. In the forthcoming days I will fix it in the README.
In the meantime, you can use this instead:
`
all_approved_eic() |> 
    filter(EicLongName == "Germany") |>
    glimpse()
`
Thank you for checking the repo!
Regards,
Sandor

**Comment by sbudai** [comment]
The README has been readjusted in version 0.7.1.1
Thanks for your patience!
