### ISSUE TITLE
Y_eiccodes.csv file downloaded on every request

### ISSUE THREAD

**Issue by sergejlazuk** [krose/entsoeapi#32]
HI,
it seems that "Y_eiccodes.csv" file is doenloaded on every request, which slows the things down, e.g. in "gen_wind_solar_forecasts" I see these messages:
```
downloading https://eepublicdownloads.entsoe.eu/eic-codes-csv/Y_eiccodes.csv file
```
3 times!
It seems not optimal.
Maybe one could download this file once and add it to "data" folder so that it is loaded once packge is loaded, as I think these codes are not changing that offten?
Thx,
Sergej

**Comment by sbudai** [comment]
The new version is out. I versioned as 0.7.2.0. It contains the awaited caching mechanism.
