### ISSUE TITLE
en_generation_agg_gen_per_type function on a Mac

### ISSUE THREAD

**Issue by jfd118** [krose/entsoeapi#9]
I recently switched from a Windows machine to a Mac running Monterey.    In windows in had no issue with entsoeapi. 

On the mac, when I use the function en_generation_agg_gen_per_type, I receive an error.    If I run the API call directly in a browser: 

CALL: https://transparency.entsoe.eu/api?documentType=A75&processType=A16&in_Domain=10Y1001A1001A83F&periodStart=2021-01-01&periodEnd=2021-12-31%2023:00:00&securityToken=YOUR_TOKEN

RESPONSE: <Acknowledgement_MarketDocument xmlns="urn:iec62325.351:tc57wg16:451-1:acknowledgementdocument:7:0">
<mRID>4ed90d04-8b2f-4</mRID>
<createdDateTime>2022-04-10T12:23:23Z</createdDateTime>
<sender_MarketParticipant.mRID codingScheme="A01">10X1001A1001A450</sender_MarketParticipant.mRID>
<sender_MarketParticipant.marketRole.type>A32</sender_MarketParticipant.marketRole.type>
<receiver_MarketParticipant.mRID codingScheme="A01">10X1001A1001A450</receiver_MarketParticipant.mRID>
<receiver_MarketParticipant.marketRole.type>A39</receiver_MarketParticipant.marketRole.type>
<received_MarketDocument.createdDateTime>2022-04-10T12:23:23Z</received_MarketDocument.createdDateTime>
<Reason>
<code>999</code>
<text>Expected parameter value length is 12. Delivered parameter: PeriodEnd, value 2021-01-01</text>
</Reason>
</Acknowledgement_MarketDocument>

The ENTSOE API does not like the PeriodEnd.  I've tried different variations but none work.  I.e, 2021-01-01 00:00 or 2021-01-01 00:00:00, adding "UTC", etc. 

So, something changes in the formatting of the request between windows and Mac.   Have you run into this before?

**Comment by krose** [comment]
Hi @jfd118 I've just updated the function. Can you try to install the latest and try this out:

```
en_generation_agg_gen_per_type(eic = "10Y1001A1001A83F", period_start = lubridate::ymd("2022-01-01", tz = "CET"),period_end = lubridate::ymd("2022-01-05", tz = "CET"), gen_type = "B14")
```
Your request returns more than 600K rows, so I've just made a sligtly smaller one.

**Comment by jfd118** [comment]
Hi,  Thank you for trying to correct the issue.  Unfortunately, after installing and running your request I get the same result.

**Comment by jfd118** [comment]
That is wrong.  For some reason the period_start = lubridate(..) and period= ...   statements don't work. 
I hard coded Jan 1 to Jan 5.  The result is: 
Error in en_gen_agg_gen_pertype_api_req_helper(eic = eic, period_start = period_start2,  : 
  object 'period_start2' not found
In addition: Warning messages:
1: The 2022-01-01 CET value interpreted as UTC. 
2: The 2022-01-05 CET value interpreted as UTC.

**Comment by krose** [comment]
I see it fails on trying to find an object called period_start2, which I just removed. Can I see your session info please?

```
devtools::session_info()

```

**Comment by jfd118** [comment]
Hi, devtools::session_info() output: 
─ Session info ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 setting  value
 version  R version 4.1.2 (2021-11-01)
 os       macOS Monterey 12.3
 system   aarch64, darwin20
 ui       RStudio
 language (EN)
 collate  en_US.UTF-8
 ctype    en_US.UTF-8
 tz       America/New_York
 date     2022-04-11
 rstudio  2022.02.0+443 Prairie Trillium (desktop)
 pandoc   NA

**Comment by krose** [comment]
How did the `lubridate::ymd("2022-01-05", tz = "CET")` evaluate?

I'm looking for the packages too as versions sometimes create a mess.. Here is a smal snippet of mine:


```
- Session info --------------------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 4.1.2 (2021-11-01)
 os       Windows 10 x64              
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  Danish_Denmark.1252         
 ctype    Danish_Denmark.1252         
 tz       Europe/Paris                
 date     2022-04-11                  

- Packages ------------------------------------------------------------------------------------------------------------------------------------
 package       * version date       lib source                         
 assertthat      0.2.1   2019-03-21 [1] CRAN (R 4.1.1)                 
 backports       1.3.0   2021-10-27 [1] CRAN (R 4.1.1)                 
 base64enc       0.1-3   2015-07-28 [1] CRAN (R 4.1.1)                 
 bit             4.0.4   2020-08-04 [1] CRAN (R 4.1.1)                 
 bit64           4.0.5   2020-08-30 [1] CRAN (R 4.1.1)                 
 blob            1.2.2   2021-07-23 [1] CRAN (R 4.1.1)                 
 broom           0.7.10  2021-10-31 [1] CRAN (R 4.1.1)                 
 bslib           0.3.1   2021-10-06 [1] CRAN (R 4.1.2)                 
 cachem          1.0.6   2021-08-19 [1] CRAN (R 4.1.1)                 
 callr           3.7.0   2021-04-20 [1] CRAN (R 4.1.1)                 
 cellranger      1.1.0   2016-07-27 [1] CRAN (
```

**Comment by jfd118** [comment]
So, before retrieving the session info I decided to start with a clean restart of Rstudio.   I worked on several R scripts over the weekend each of which were still open.  Having restarted RStudio and running your test called (above) to the function en_generation_agg_gen_per_type the data is properly retrieved. 

I suppose this suggests a package conflict but we won't know which one.  

The current session info (returning the ENTSO-E data properly) is below. 



─ Session info ────────────────────────────────────────────────────────────────────────────────────────────
 setting  value
 version  R version 4.1.2 (2021-11-01)
 os       macOS Monterey 12.3
 system   aarch64, darwin20
 ui       RStudio
 language (EN)
 collate  en_US.UTF-8
 ctype    en_US.UTF-8
 tz       America/New_York
 date     2022-04-11
 rstudio  2022.02.0+443 Prairie Trillium (desktop)
 pandoc   NA

─ Packages ────────────────────────────────────────────────────────────────────────────────────────────────
 package     * version date (UTC) lib source
 assertthat    0.2.1   2019-03-21 [1] CRAN (R 4.1.0)
 backports     1.4.1   2021-12-13 [1] CRAN (R 4.1.1)
 brio          1.1.3   2021-11-30 [1] CRAN (R 4.1.1)
 broom         0.7.12  2022-01-28 [1] CRAN (R 4.1.1)
 cachem        1.0.6   2021-08-19 [1] CRAN (R 4.1.1)
 callr         3.7.0   2021-04-20 [1] CRAN (R 4.1.0)
 cellranger    1.1.0   2016-07-27 [1] CRAN (R 4.1.0)
 cli           3.2.0   2022-02-14 [1] CRAN (R 4.1.1)
 colorspace    2.0-3   2022-02-21 [1] CRAN (R 4.1.1)
 crayon        1.5.1   2022-03-26 [1] CRAN (R 4.1.1)
 curl          4.3.2   2021-06-23 [1] CRAN (R 4.1.0)
 data.table    1.14.2  2021-09-27 [1] CRAN (R 4.1.1)
 DBI           1.1.2   2021-12-20 [1] CRAN (R 4.1.1)
 dbplyr        2.1.1   2021-04-06 [1] CRAN (R 4.1.0)
 desc          1.4.1   2022-03-06 [1] CRAN (R 4.1.2)
 devtools      2.4.3   2021-11-30 [1] CRAN (R 4.1.1)
 dplyr       * 1.0.8   2022-02-08 [1] CRAN (R 4.1.1)
 ellipsis      0.3.2   2021-04-29 [1] CRAN (R 4.1.0)
 entsoeapi   * 0.1.4   2022-04-11 [1] Github (krose/entsoeapi@cd22de4)
 fansi         1.0.3   2022-03-24 [1] CRAN (R 4.1.1)
 fastmap       1.1.0   2021-01-25 [1] CRAN (R 4.1.0)
 feather     * 0.3.5   2019-09-15 [1] CRAN (R 4.1.0)
 forcats     * 0.5.1   2021-01-27 [1] CRAN (R 4.1.1)
 fs            1.5.2   2021-12-08 [1] CRAN (R 4.1.1)
 generics      0.1.2   2022-01-31 [1] CRAN (R 4.1.1)
 ggplot2     * 3.3.5   2021-06-25 [1] CRAN (R 4.1.1)
 glue          1.6.2   2022-02-24 [1] CRAN (R 4.1.1)
 gtable        0.3.0   2019-03-25 [1] CRAN (R 4.1.1)
 haven         2.4.3   2021-08-04 [1] CRAN (R 4.1.1)
 hms           1.1.1   2021-09-26 [1] CRAN (R 4.1.1)
 httr          1.4.2   2020-07-20 [1] CRAN (R 4.1.0)
 jsonlite      1.8.0   2022-02-22 [1] CRAN (R 4.1.1)
 lifecycle     1.0.1   2021-09-24 [1] CRAN (R 4.1.1)
 lubridate   * 1.8.0   2021-10-07 [1] CRAN (R 4.1.1)
 magrittr      2.0.3   2022-03-30 [1] CRAN (R 4.1.1)
 memoise       2.0.1   2021-11-26 [1] CRAN (R 4.1.1)
 modelr        0.1.8   2020-05-19 [1] CRAN (R 4.1.0)
 munsell       0.5.0   2018-06-12 [1] CRAN (R 4.1.0)
 pillar        1.7.0   2022-02-01 [1] CRAN (R 4.1.1)
 pkgbuild      1.3.1   2021-12-20 [1] CRAN (R 4.1.1)
 pkgconfig     2.0.3   2019-09-22 [1] CRAN (R 4.1.0)
 pkgload       1.2.4   2021-11-30 [1] CRAN (R 4.1.1)
 prettyunits   1.1.1   2020-01-24 [1] CRAN (R 4.1.0)
 processx      3.5.2   2021-04-30 [1] CRAN (R 4.1.0)
 ps            1.6.0   2021-02-28 [1] CRAN (R 4.1.0)
 purrr       * 0.3.4   2020-04-17 [1] CRAN (R 4.1.0)
 R6            2.5.1   2021-08-19 [1] CRAN (R 4.1.1)
 Rcpp          1.0.8   2022-01-13 [1] CRAN (R 4.1.1)
 readr       * 2.1.2   2022-01-30 [1] CRAN (R 4.1.1)
 readxl        1.3.1   2019-03-13 [1] CRAN (R 4.1.0)
 remotes       2.4.2   2021-11-30 [1] CRAN (R 4.1.1)
 reprex        2.0.1   2021-08-05 [1] CRAN (R 4.1.1)
 rlang         1.0.2   2022-03-04 [1] CRAN (R 4.1.1)
 rprojroot     2.0.2   2020-11-15 [1] CRAN (R 4.1.0)
 rstudioapi    0.13    2020-11-12 [1] CRAN (R 4.1.0)
 rvest         1.0.2   2021-10-16 [1] CRAN (R 4.1.1)
 scales        1.1.1   2020-05-11 [1] CRAN (R 4.1.0)
 sessioninfo   1.2.2   2021-12-06 [1] CRAN (R 4.1.1)
 stringi       1.7.6   2021-11-29 [1] CRAN (R 4.1.1)
 stringr     * 1.4.0   2019-02-10 [1] CRAN (R 4.1.1)
 testthat      3.1.2   2022-01-20 [1] CRAN (R 4.1.1)
 tibble      * 3.1.6   2021-11-07 [1] CRAN (R 4.1.1)
 tidyr       * 1.2.0   2022-02-01 [1] CRAN (R 4.1.1)
 tidyselect    1.1.2   2022-02-21 [1] CRAN (R 4.1.1)
 tidyverse   * 1.3.1   2021-04-15 [1] CRAN (R 4.1.0)
 tzdb          0.2.0   2021-10-27 [1] CRAN (R 4.1.1)
 usethis       2.1.5   2021-12-09 [1] CRAN (R 4.1.1)
 utf8          1.2.2   2021-07-24 [1] CRAN (R 4.1.0)
 vctrs         0.4.0   2022-03-30 [1] CRAN (R 4.1.1)
 withr         2.5.0   2022-03-03 [1] CRAN (R 4.1.1)
 xml2          1.3.3   2021-11-30 [1] CRAN (R 4.1.1)

**Comment by krose** [comment]
I've experienced that updating packages from one window of RStudio while have the same package attached to the environment in another, can cause the newer package version not to install. But glad it works for you again. I'll close the issue.

**Comment by jfd118** [comment]
Thank you for your help.
